### PR TITLE
[BUGFIX] Fix wrong execution path with coreapi

### LINKED ISSUE #73: Commands using 'typo3/cli_dispatch.phpsh' should take webDirectory into account
Current tasks running 'typo3/cli_dispatch.phpsh' will fail because they get executed in the project root directory instead of the webDirectory (if that is in use, of course).

i.e. https://github.com/TYPO3/Surf/blob/master/src/Task/TYPO3/CMS/FlushCachesTask.php#L59 will fail if caches should be cleared using coreapi.

### PR DESCRIPTION
**Pull request by sabbelasichon**
- Fixes #73

### CODE REVIEW

File: src/Task/TYPO3/CMS/AbstractCliTask.php [hunk 1]
```diff
@@ -202,4 +202,15 @@ protected function ensureApplicationIsTypo3Cms(Application $application)
...
+
+    /**
+     * @param array $options
+     *
+     * @return string
+     */
+    protected function getCliDispatchScriptFileName(array $options = array())
+    {
+        $webDirectory = isset($options['webDirectory']) ? trim($options['webDirectory'], '\\/') : '';
+        return $webDirectory !== '' ? sprintf('%s/typo3/cli_dispatch.phpsh', $webDirectory) : 'typo3/cli_dispatch.phpsh';
```
Comment (tstahn) [inline src/Task/TYPO3/CMS/AbstractCliTask.php]: The entry ponit `typo3/cli_dispatch.phpsh`is deprecated since TYPO3 v8, we need to keep that in mind.

Comment (sabbelasichon) [reply src/Task/TYPO3/CMS/AbstractCliTask.php]: Any quick suggestions, what we can do? I think no one is using coreapi anyway in version TYPO3 8

Comment (tstahn) [reply src/Task/TYPO3/CMS/AbstractCliTask.php]: It won't be removed until TYPO3 9 anyway, so we should be fine with keeping it in until then. If it turns out that no one is using the Core API anyway, we could consider dropping support for it. 

I don't feel like there is any need to add for new functionality/configuration options here.
